### ISSUE TITLE
CLPHelper is undefined

### ISSUE THREAD

**Issue by isokosan** [dodi-smart/parse-server-typescript#15]
Hi! Thanks for this repo! I was just setting it up and noticed the `CLPHelper` on the `SchemaMigrations` does not exist and leads to an undefined error from `ts-node`. Any ideas what this could be about? For now, I removed the below line and use object definitions for the CLP to get it working. But would love to learn more about this CLPHelper, if it still exists in parse-server.

```
$ TS_NODE_FILES=true node --require ts-node/register --trace-warnings ./src/index.ts
/home/deniz/dev/examples/parse-server-typescript/src/schema/User.schema.ts:32
        ...SchemaMigrations.CLPHelper.requiresAuthentication(["find", "count", "get"]),
                                      ^
TypeError: Cannot read properties of undefined (reading 'requiresAuthentication')
    at Object.<anonymous> (/home/deniz/dev/examples/parse-server-typescript/src/schema/User.schema.ts:32:39)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (/home/deniz/dev/examples/parse-server-typescript/node_modules/ts-node/src/index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/home/deniz/dev/examples/parse-server-typescript/node_modules/ts-node/src/index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/deniz/dev/examples/parse-server-typescript/src/schema/index.ts:2:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by azlekov** [comment]
Thanks @isokosan! 

I will check upcoming days what was the case with the defined schemas.

I saw that you made some improvements on your fork - it would be great if you open a PR to have them here (nodemon, module aliases eslint etc.)✌️

**Comment by isokosan** [comment]
Would be awesome! Found that most definitions are now added in [`Migrations.js`](https://github.com/parse-community/parse-server/blob/alpha/src/SchemaMigrations/Migrations.js) by the way, I couldn't get code completion to pick them up though.

**Comment by isokosan** [comment]
I changed the linting rules to my preference, so I'll roll those back when I get the time and do a PR!

**Comment by azlekov** [comment]
@isokosan can you check this: https://github.com/dodi-smart/parse-server-typescript/pull/16
